---
title: "ONBOARDING"
author: "Neha Moopen"
date: "30-6-2021"
output: 
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
    toc: true
    toc_depth: 1
---

# WELCOME

Welcome to Utrecht University Library, Dorien! This onboarding document is meant to help you get you acquainted with our organization and team. For questions, you can contact me - your 'buddy' [Neha Moopen](n.moopen@uu.nl). You can also ask any colleague who happens to be around!

I hope this document will be useful and you have a nice start at the UB. I'll be around for any and all questions. And as my previous buddy emphasized for me, HAVE FUN! 

# GETTING STARTED

For your general administrative & HR-related practicalities, the [UU Intranet](intranet.uu.nl) is a good start! There is a whole section on _Information for New Employees_ that you can go through.

## Practical Things

Here's a checklist of things you can cover in your first days:

**Arrange Hardware & Software**

- [ ] Laptop
- [ ] Phone
- [ ] [Two-Factor Authentication](https://intranet.uu.nl/en/2fa)
- [ ] [VPN](https://manuals.uu.nl/en/handleiding/u-and-o-drive-on-windows-10-vpn/)

**Staff Access**

- [ ] UBU Employee Card
- [ ] [UU Campus Card](https://intranet.uu.nl/en/knowledgebase/campus-card)

**Administration & HR**

- [ ] Check out [Self-Service HR](https://selfservice.portal.uu.nl/irj/portal/hr/medewerker). 
- [ ] Fill in your work schedule on Self-Service HR
- [ ] Update your [personal profile page](https://intranet.uu.nl/en/knowledgebase/about-the-profile-pages)
- [ ] Check out [TopDesk](http://uu.topdesk.net/) - a self-service portal.

## New Staff Orientation Session

New staff members are always invited to an [orientation session](https://intranet.uu.nl/en/knowledgebase/new-staff-orientation-session). These take place 5 times a year. You'll receive an invitation via email about 4-6 weeks prior to the next meeting. 

Mine was online, I can't be sure sure if you'll get to attend an offline one. You'll find out soon enough!

## Campus Map

You likely know your way around as a UU-alum, but here's a [link](https://intranet.uu.nl/en/knowledgebase/buildings-and-maps) to maps of the campus - just in case you need them!

# UNIVERSITY LIBRARY

AKA. The coolest building(s) on campus.

## The UB: General

The Library consists of three divisions/sectors:

- Collection Services

- Academic Services 

- Public Services 

There is also: 

- _Stafdiensten_ which includes management support, communications, IT, facility management.

You can read the UB's [Strategic Plan](https://www.uu.nl/sites/default/files/strategisch_plan_ub_2018-2020_engelstalig.pdf) here, but a new version will probably come along soon.

## The UB: Offline

As you know, the UB is situated in two locations: the Binnenstad (UBB) & Utrecht Science Part (USP). You'll mostly work at the USP, at the offices on the 2nd floor.  

We are still primarily working from home, but can choose to work on location once a week or so. For this you have to reserve a werkplek and there's a Teams group (and Excel sheet within the Teams) to arrange this - _Reserveren werkplek UB_. You'll also be added to this group automatically.

FYI: Rooms 2.14 & 2.16 are the ones where most Academic Services/RDM Support staff work (as far as I know, I've been a 100% thuiswerker all this while).

## The UB: Online

- The UB has it's own [intranet](http://intranet.library.uu.nl), but FYI we are going to be migrating to a space _within_ the UU Intranet very soon. So maybe don't bookmark this link :P

- During coronatimes, the UB has it's own _UB Koffiehoek_ on Teams. You will be added to this group automatically. 

## Introductory Meetings

- You will be invited to an introduction meeting with Anja Smit (University LIbrary / Director of the Library).

- You will also be invited to an _Introductiebijeenkomst voor nieuwe medewerkers'_.

## UB-wide meetings

- I(dee) D(elen) koffie
- I&D Bijeenkomst

You'll be invited to these automatically. These are meetings where colleagues across sectors come together to share updates and ideas.

## Bonus!

- If you would like to meet more of your colleagues in the UB, you can join the _Mystery Coffee_ organized within the UB Koffiehoek! 

# ACADEMIC SERVICES

This is our sector! 

## The Bosses

The manager of our sector include:

- **Division Manager**: Martine Pronk
- **Department Manager**: Coen Wilders (UBB)
- **Department Manager**: Kim Bergmans (USP)

Kim is our manager, so you'll be in touch with all the time. You'll be invited to (re-)introduction meetings with Martine & Coen.

## Faculty Liasions

To learn more about both our services and relations with respect to the UU faculties it is good to have meetings with faculty liaisons. They are considered to be the ones with in-depth knowledge about ‘who is who’ at the faculty-level. Faculty liaisons are the contacts of representation of the library at the faculties. Therefore, make an appointment with: 

- [ ] **Science**: Aleksandre Gogaladze
- [ ] **Veterinary Sciences**: Felix Weijdema
- [ ] **Humanities**: Rogier Schumacher
- [ ] **Medical Sciences**: Paulien Wiersma
- [ ] **Geosciences**: Jeroen Bosman
- [ ] **Law, Economics, and Government**: Sandrien Banens
- [ ] **Social Sciences**: Jan de Boer

## AS Teams

Academic Services is further organized into teams. For management purposes, these teams are divided between Coen & Kim. Each team has a contact person (or _aanspreekpunt_). It would be helpful to meet these contact persons and learn about what each team does and how we all fit together within the sector:

- [ ] **OPERA (no, not the Library Choir)**: Felix Weijdema
- [ ] **Coding & Software**: N/A, you can talk to Neha/Bianca/Jacques
- [ ] **Digital Humanities Support**: Puck Wildschut
- [ ] **Special Collections**: Marco van Egmond
- [ ] **Learning**: Wieteke Janssen *
- [ ] **ADD**: Desiree ten Dam & Rogier Schumacher
- [ ] **RDM Support**: Annemiek van der Kuil ** 
- [ ] **Publishing Support**: Fleur Stigter
- [ ] **Copyright Information Office**: Margriet Fokken & Judith Hanekuijk
- [ ] **BONUS -> Open Access Specialist:** Jeroen Sondervan

** Wieteke is leaving the UB soon, I need to double-check who is 'officially' her replacement as contact person for Team Learning.

*** Annemiek is currently out of office, so Neha (and the rest of RDM Support) will get you up to speed.

## AS Meetings

Currently, Academic Services gets together (via MS Teams) for a meeting every week or so. These are just called the 'AS Meetings' and you will be invited to them automatically.They are not mandatory, but I'd recommend to attend them regularly.   

During these meetings, there is usually one presentation which serves as an update of what a particular person's/team's has been up to. 

The meetings are 30 minutes long. I have lost some sense of time due to the coronalife and I forgot how frequent they: weekly? biweekly? We have to ask Kim.

# RDM SUPPORT

This is your team! We are so happy to have you join us! <insert dancing The Office gif here>

Take some time to go through the RDM Support [website](https://www.uu.nl/en/research/research-data-management). It's our go-to page for researchers and staff. We also have a newsletter you should subscribe to.

You can also read the [University Framework for Research Data UU](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf). Faculties have their specific policies but this overarching one is a start.

## RDM within UB

**RDM Support Coordinator**

- [ ] Annemiek van der Kuil (out of office)

**Data Consultants**

- [ ] Mary Felix-Maina
- [ ] Jacques Flores

**Data Managers:** 

- [ ] Ron Scholten
- [ ] Danny de Koning-van Nieuwamerongen
- [ ] Otto Lange
- [ ] Neha Moopen

**Subject Specialists:** 

- [ ] Marie-Louise Goudeau
- [ ] Puck Wildschut 
- [ ] Sandrien Banens

As a start, you can plan a meeting with each members of each 'group' together. 

## RDM beyond the UB

RDM Support is a collaboration between the University Library (UB) & Information Technology Services (ITS). 

The Department Manager of ITS is Frank Heere. Within ITS, the **Research Engineering** team and **Yoda Development Team** are ones that we collaborate with a lot. 

The larger RDM Support 'network' also includes the Privacy Officers, Information Security, Research Support Officers.

As a start, you can plan meetings with the following people:

- [ ] **Research Engineering**: Martine de Vos

- [ ] **Privacy**: Sanne Kleerebezem

- [ ] **Information Security**

## Meetings 

Meetings for RDM Support occur at different levels:

- [ ] **DMDC meeting:** Monthly meetings of the Data Consultants & Data Managers to update one another.

- [ ] **RDM Askathon:** A wholly informal and non-mandatory meeting of RDM colleagues within the library to ask each other RDM questions and learn from one another.

- [ ] **D-Lunch:** A monthly informal meeting with people from
the larger RDM support network. Not mandatory, but recommended for a newbie.

- [ ] **RDM Expert Meeting:** A semi-formal meeting with people from the larger RDM Support network to dive into + discuss RDM-specific topics and issues.

- [ ] **UDMC Meeting:** I think we've only had one of these so far, and has been put on hold as Annemiek is out of office. It is a longer event with pre-planned presentations on major topics/developments within RDM Support.

## Teams

Make sure you're part of 2x teams for RDM Support: the _RDM Support_ team itself and also the _Utrecht Data Management Community_.

## BONUS: Open Science Community Utrecht

Not specifically RDM-focused, but a very important space to keep up with researchers!

You can register on their [website](https://openscience-utrecht.com/). 

They usually organize an _OSCoffee_ every month and there are larger faculty-specific open science symposiums organized through the year.

OSCU also has a Slack group that you can join!

# LINKS & MORE LINKS

The actual links will be updated!

- UU Strategic Plan
- An [overview](https://intranet.uu.nl/kennisbank/abonneren-op-nieuwsbrieven) of ALL the UU newsletters. Subscribe to the ones you want!
- Landelijk Coordinatepunt Research Data Management (LCRDM)
- LCRDM Mailing List
- National Platform Open Science & NAtional Plan Open Science (NPOS)
- JISC
- JISC (UK) Research Data Management dicussion list
- LIBER
- Australian Research Data Commons (ARDC)
- Research Data Alliance (RDA)
- Open Data Institute (ODI)
- Open Knowledge Foundation (OKF)
- FAIRsFAIR
- Health-RI
- DANS
- CESSDA
- DDI
- GO-FAIR
- UK Data Service